import MMarket from "../../assets/main/Proeyctos/MMarket.svg";
import RecipeFood from "../../assets/main/Proeyctos/RecipeFood.png";
import JCDV from "../../assets/main/Proeyctos/JCDV.svg";
import Tn from "../../assets/main/Proeyctos/Tn.png";

export const proyectsData = [
    {
      tecnologias: [
        "HTML",
        "REACT",
        "JAVASCRIPT",
        "TAILWIND",
        "GITHUB",
      ],
      titulo: "Jesus Camino de Vida",
      fecha: "20 - jul - 20 Dic - 2023",
      github: "github.com/JuanJose",
      web: "github.com/JuanJose",
      image: JCDV,
      gridArea: "bigTopLeft",
      descripcion: "sssss",
    },
    {
      tecnologias: [
        "HTML",
        "CSS",
        "REACT",
        "JAVASCRIPT",
        "REDUX",
        "NODE",
        "EXPRESS",
        "POSTGRESQL",
        "GITHUB",
      ],
      titulo: "Recipe Food",
      fecha: "20 Jul - 30 Ago - 2023",
      github: "github.com/JuanJose",
      web: "github.com/JuanJose",
      image: RecipeFood,
      gridArea: "minTopCenter",
      short: true,
      descripcion: "sss",
    },
    {
      tecnologias: [
        "HTML",
        "REACT",
        "JAVASCRIPT",
        "TAILWIND",
        "GITHUB",
      ],
      titulo: "IJCDV",
      fecha: "20 Jul - 30 Ago - 2023",
      github: "github.com/JuanJose",
      web: "github.com/JuanJose",
      image: JCDV,
      gridArea: "bigTopRight",
      descripcion: "sss",
    },
    {
      tecnologias: [
        "HTML",
        "CSS",
        "REACT",
        "JAVASCRIPT",
        "TYPESCRIPT",
        "SASS",
        "REDUX",
        "GITHUB",
      ],
      titulo: "TN",
      fecha: "20 Jul - 30 Ago - 2023",
      github: "github.com/JuanJose",
      web: "github.com/JuanJose",
      image: Tn,
      gridArea: "bigBotCenter",
      short: true,
      descripcion: "uhihiu",
    },
    {
      tecnologias: [
        "HTML",
        "CSS",
        "REACT",
        "JAVASCRIPT",
        "REDUX",
        "NODE",
        "EXPRESS",
        "POSTGRESQL",
        "GIT",
        "GITHUB",
      ],
      titulo: "MMarket",
      fecha: "20 Jul - 30 Ago - 2023",
      github: "github.com/JuanJose",
      web: "github.com/JuanJose",
      image: MMarket,
      gridArea: "minBotRight",
      descripcion:
        "MMarket simplifica compras en tiendas locales a través de su plataforma en línea, beneficiando a tiendas y usuarios con opciones de compra en persona y entregas a domicilio. Su objetivo es ampliar su alcance.",
    },
  ]